[package]
name = "pallet-evm-precompile-curve25519"
version = "1.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>", "Drew Stone <drew@webb.tools>"]
edition = "2021"
rust-version = "1.56.1"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/frontier/"
description = "Curve25519 elliptic curve precompiles for EVM pallet."

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
sp-core = { version = "5.0.0", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-io = { version = "5.0.0", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
frame-support = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

fp-evm = { version = "3.0.0-dev", default-features = false, path = "../../../../primitives/evm" }

[dependencies.curve25519-dalek]
version = "4.0.0-dev"
default-features = false
features = ["u64_backend", "alloc"]

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-core/std",
	"sp-io/std",
	"frame-support/std",
	"fp-evm/std",
]
