[package]
name = "pallet-evm-precompile-curve25519"
version = "1.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>", "Drew Stone <drew@webb.tools>"]
edition = "2021"
rust-version = "1.56.1"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/frontier/"
description = "Curve25519 elliptic curve precompiles for EVM pallet."

[dependencies]
curve25519-dalek = { version = "4.0.0-dev", default-features = false, features = ["u64_backend", "alloc"] }

fp-evm = { version = "3.0.0-dev", default-features = false, path = "../../../../primitives/evm" }

[features]
default = ["std"]
std = [
	"fp-evm/std",
]
