[package]
name = "pallet-evm-precompile-dispatch"
version = "2.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
rust-version = "1.56.1"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/frontier/"
description = "DISPATCH precompiles for EVM pallet."

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
sp-core = { version = "5.0.0", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-io = { version = "5.0.0", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
frame-support = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

fp-evm = { version = "3.0.0-dev", default-features = false, path = "../../../../primitives/evm" }
pallet-evm = { version = "6.0.0-dev", default-features = false, path = "../.." }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-core/std",
	"sp-io/std",
	"frame-support/std",
	"fp-evm/std",
	"pallet-evm/std",
]
